## Tensor Basics

In [2]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor([1., 2, 3, 4])
t2
#all elements in tensor must have the same data type, if not torch will convert.

tensor([1., 2., 3., 4.])

In [7]:
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3
#it should have a regular shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t2.shape

torch.Size([4])

In [10]:
t3.shape

torch.Size([3, 2])

## Tensor Operations

In [11]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

In [13]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [16]:
#finding the gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(2.)


In [17]:
import numpy as np

In [18]:
x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [20]:
#covert numpy array to torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [21]:
x.dtype

dtype('float64')

In [22]:
y.dtype

torch.float64

In [23]:
#covert tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])