### Linear Regression using PyTorch

In [154]:
import numpy as np 
import torch

In [155]:
#Input training data: temperature, rainfall, humidity
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')
inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [156]:
#Targeted value, yield for: apples, oranges
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')
targets

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)

In [157]:
inputs = torch.from_numpy(inputs)

print(inputs)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [158]:
targets = torch.from_numpy(targets)

print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


### Linear Regression from scratch

In [159]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[ 0.2940, -1.0227,  0.0735],
        [-0.8381,  0.3997,  0.3350]], requires_grad=True)
tensor([ 1.8894, -1.7210], requires_grad=True)


In [160]:
def model(x):
    return x @ w.t() + b 
# @ represents matrix multiplication in pytorch and .t() returns the transpose of the tensor

In [161]:
preds = model(inputs)
print(preds)

tensor([[ -42.0090,  -21.7132],
        [ -56.6507,  -21.3693],
        [-105.3132,   -1.6393],
        [  -9.3772,  -57.6206],
        [ -70.8606,    2.2759]], grad_fn=<AddBackward0>)


In [162]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [163]:
# predictions are a way apart from the targets because the weights are randomly initialized
# Mean Squared Error Loss

def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff*diff) / diff.numel()

In [164]:
loss = mse(preds, targets)
print(loss)

tensor(17417.2793, grad_fn=<DivBackward0>)


## Computing Gradients

In [165]:
loss.backward()

In [166]:
print(w)
print(w.grad)

tensor([[ 0.2940, -1.0227,  0.0735],
        [-0.8381,  0.3997,  0.3350]], requires_grad=True)
tensor([[-10878.5947, -13355.5342,  -7873.0791],
        [ -9449.9102, -10045.8301,  -6251.2061]])


In [167]:
print(b)
print(b.grad)

tensor([ 1.8894, -1.7210], requires_grad=True)
tensor([-133.0421, -112.0133])


In [168]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [169]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [170]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)


tensor(17417.2793, grad_fn=<DivBackward0>)


In [171]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [172]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)


tensor(17417.2793, grad_fn=<DivBackward0>)
